In [2]:
import numpy as np 
import pandas as pd

In [3]:
credit_card_data=pd.read_csv('/workspaces/machine-leaarning-/zdoordie/ml/4_data collection_and_preprocessing/4_credit_data.csv')

In [4]:
credit_card_data.head(7)

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0.0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0.0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0.0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0.0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0.0
5,2.0,-0.425966,0.960523,1.141109,-0.168252,0.420987,-0.029728,0.476201,0.260314,-0.568671,...,-0.208254,-0.559825,-0.026398,-0.371427,-0.232794,0.105915,0.253844,0.081080,3.67,0.0
6,4.0,1.229658,0.141004,0.045371,1.202613,0.191881,0.272708,-0.005159,0.081213,0.464960,...,-0.167716,-0.270710,-0.154104,-0.780055,0.750137,-0.257237,0.034507,0.005168,4.99,0.0

In [5]:
credit_card_data

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0.0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0.0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0.0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0.0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
187762,127681.0,1.901463,0.552643,-0.481182,3.944113,0.335964,-0.109623,0.231971,-0.187992,-0.831883,...,0.094315,0.510277,0.063329,0.078412,0.173760,0.089763,-0.018818,-0.046877,11.36,0.0
187763,127681.0,2.100227,0.321608,-2.548285,0.458166,0.954416,-1.241859,0.742498,-0.464969,0.052797,...,0.039094,0.303052,-0.025310,0.665022,0.398541,0.684355,-0.099843,-0.050888,9.98,0.0
187764,127681.0,2.235807,-0.996976,-1.058469,-1.124942,-0.420362,0.189049,-1.026023,-0.017699,0.143828,...,0.253659,0.790709,0.025014,-0.269973,0.024299,-0.058008,0.005059,-0.049810,19.95,0.0
187765,127681.0,-0.999690,0.681567,-2.753857,-0.374143,1.728585,-1.147355,0.960126,0.222585,-0.495079,...,0.446861,1.870864,0.598747,0.285610,-0.878531,-0.170582,0.071505,-0.096012,5.00,0.0
187766,127682.0,1.910744,-0.885991,-0.392436,0.947652,-0.961851,-0.222081,-0.565175,-0.049449,0.162247,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
credit_card_data['Class'].value_counts()

# 0.0 legit tranctons , 1-> non legit transactions

Class
0.0    187398
1.0       368
Name: count, dtype: int64

In [7]:
legit_trans=credit_card_data[credit_card_data.Class==0]
non_legit_trans=credit_card_data[credit_card_data.Class==1]

In [8]:
print(legit_trans.shape)
print(non_legit_trans.shape)

(187398, 31)
(368, 31)

# Under Sampling 
Building an sample dataset containing similar distribution of legit and non legit (fraudlent)transactions

In [16]:
# takig approx mix points in the legitsample
legit_sample=legit_trans.sample(n=368)

In [17]:
legit_sample.shape

(368, 31)

concatenate the two dataframes

In [18]:
new_dataset=pd.concat([legit_sample,non_legit_trans],axis=0)

In [19]:
new_dataset.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
62362,50240.0,-0.934154,0.705075,1.991370,-0.360965,0.970368,0.176795,1.253626,-0.270610,-0.473439,...,0.080142,0.449368,-0.513561,-0.312994,0.590772,-0.449392,-0.404480,-0.406506,39.99,0.0
39238,39756.0,1.414655,-1.235626,0.463856,-1.413847,-1.640605,-0.407983,-1.263916,0.172810,-1.722932,...,-0.151309,-0.176694,0.107904,0.141437,0.167596,-0.198424,0.025300,0.004120,15.00,0.0
72869,54891.0,1.295257,0.400235,-1.832616,0.133846,2.551452,3.060135,-0.285335,0.756222,-0.209661,...,-0.105513,-0.385454,-0.154808,0.881591,0.849888,-0.311819,0.034099,0.044344,1.00,0.0
116184,74174.0,1.238251,-0.287397,0.052777,0.198944,-0.173361,0.302150,-0.319236,0.152271,0.675870,...,-0.120459,-0.219052,-0.243750,-0.772835,0.625363,0.726763,-0.048864,-0.013374,27.83,0.0
88817,62308.0,-2.209816,-0.555353,-0.469295,0.957498,2.286729,0.046087,2.906240,-1.302464,-1.015695,...,-0.178397,1.351291,-0.089121,-0.888703,1.590244,0.358303,-0.543606,-0.633684,209.89,0.0

In [21]:
new_dataset.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
178208,123525.0,-5.904921,4.439911,-8.631802,7.788684,-4.989580,-1.200144,-7.674060,4.125761,-5.315778,...,1.775030,1.266441,-0.199410,0.014960,-0.000019,0.544210,-1.167566,-1.206354,45.51,1.0
181966,125200.0,-0.769172,1.342212,-2.171454,-0.151513,-0.648374,-0.973504,-1.706658,0.313745,-1.982302,...,-0.036122,-0.753591,-0.047113,0.358493,-0.287407,0.476506,0.250531,0.250987,40.00,1.0
182992,125612.0,1.889618,1.073099,-1.678018,4.173268,1.015516,-0.009389,-0.079706,0.064071,-0.714517,...,0.203728,0.733796,-0.036560,0.334306,0.147171,0.279556,0.031669,0.035883,3.22,1.0
183106,125658.0,0.224414,2.994499,-3.432458,3.986519,3.760233,0.165640,1.099378,-0.654557,-2.435416,...,0.491337,-0.984223,-0.421979,-1.048058,0.726412,0.268625,0.283689,0.419102,0.00,1.0
184379,126219.0,-1.141559,1.927650,-3.905356,-0.073943,-0.044858,-1.756999,-1.217416,0.364563,-2.770148,...,0.102081,-0.531496,-0.328741,0.393100,0.568435,0.786605,-0.146102,0.076211,25.00,1.0

In [22]:
new_dataset.shape

(736, 31)